version: '3'

services:
  db:
    image: 'postgres'
    restart: 'always'
    container_name: 'crypto-postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '54320:5432'