version: '3'

services:
  db:
    image: 'postgres'
    container_name: 'crypto-postgres'
    environment:
      - POSTGRES_PASSWORD=root
  app:
    build: ./
    container_name: 'cryptocurrencyalert'
    depends_on:
      - db
